sudo: required
dist: trusty
language: python

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - bash sync_to_master.sh
  - bash apply_regtest_patch.sh
  - python integration_testing.py
  - python lbryum_testing.py
notifications:
  slack:
    secure: y78pSkl/SDrE1JOTYxyDcI6DeXmwSeaDYTIxNcg6NgumRfPloXcel6N6LMBPYFYj7Jbzmo/61kF78YX9VK0BBEEupA8gYO/4q/asknvkfLMQXbbKFXouV7JVLRWWtx7upMz3IuLb+MgLKK/Mb07oxY08ehB7K5bKrenuZ8P6T1oQcf28ws1IH/poVKisCgQZ4vYp9/pk1WhJyxweJBNP67mzypuCUbj9dHxOQKiWvzFmjU0kdEmU2/Y2VqJ5J/vRPe5QSd4MRqpyzP8K17BYpYKN6ZvP5/tnPuorxL4dHarUvvRL4JAtOxjtCJ8YSz4ap0xkCSQIo8NGHlT+4u8kzCoIsWBbWoA6Cy/tyMlU8tIFvXN0nENwLNonPY5z0CzbSAybR1htYOYCeURwAu0ouC9J2yZxzSPocFq+Ws3azv80qV/Xgsp4RqdeRDXgMJrOLU0n0IOhizJU6nDgWp7d4fJTHQuPFzbPlDiE3hOFhsIyUtVmvWEX4rpRXk1x6BT6A/ckgOYXTkeAvwlpz6FjtLmIPThoD3sji6XumYo6YKBvilNvrHbnic9ZBvOCXG3jwHISKQ4efFz3MTY3uUnr1VtaqCHU7f/15CzGovHFHjKlIVK9N1j7S6aShUDY5tH2Z/l9QYBaUV0+sjQhDECgOMIdHwzdwFpTkV4ahpBHVkM=
