version: '2'


services:
  lbrycrd:
    build: ./lbrycrd
    expose:
      # lbrycrd port
      - 19000
    ports:
      # rpcport
      - 19001:19001

  lbryum-server:
    build: ./lbryum-server
    ports:
      # lbryum rpc port
      - 8000:8000
      # stratum port
      # (this is what lbryum client connects to)
      - 50001:50001
    depends_on:
      - lbrycrd

  dht:
    build: ./lbrynet
    depends_on:
      - lbryum-server
      - fake-bittrex
    environment:
      # want to be able to access this from the host
      - LBRY_API_HOST=0.0.0.0
      - LBRY_KNOWN_DHT_NODES=lbrynet:4444,reflector:4444
    expose:
      - 3333
      - 4444
    ports:
      - 5278:5279

  reflector:
    build: ./lbrynet
    depends_on:
      - lbryum-server
      - dht
      - fake-bittrex
    environment:
      - LBRY_RUN_REFLECTOR_SERVER=true
      - LBRY_API_HOST=0.0.0.0
      - LBRY_KNOWN_DHT_NODES=lbrynet:4444,dht:4444
    expose:
      - 3333
      - 4444
      - 5566
    ports:
      - 5277:5279
  lbrynet:
    build: ./lbrynet
    depends_on:
      - lbryum-server
      - dht
      - fake-bittrex
      - reflector
    environment:
      - LBRY_API_HOST=0.0.0.0
      - LBRY_ALLOWED_ORIGIN=http://localhost:5280
      - LBRY_KNOWN_DHT_NODES=dht:4444,reflector:4444
    ports:
      # the ui and the api port
      - 5279:5279
    expose:
      - 3333
      - 4444

  lbryum:
    build: ./lbrynet
    depends_on:
      - lbryum-server
    ports:
      - 7777:7777
    command: ["/app/bin/run.sh", "lbryum-only"]



  fake-bittrex:
    build: ./fake-bittrex
    expose:
      - 8003


