version: '2'

networks:
  lbry:
    driver: bridge

services:
  lbrycrd:
    build: ./lbrycrd
    ports:
      # lbrycrd port
      - 19000:19000
      # rpcport
      - 19001:19001
    networks:
      - lbry

  lbryum-server:
    build: ./lbryum-server
    ports:
      # lbryum rpc port
      - 8000:8000
      # stratum port
      # (this is what lbryum client connects to)
      - 50001:50001
    depends_on:
      - lbrycrd
    networks:
      - lbry

  dht:
    build: ./lbrynet
    depends_on:
      - lbryum-server
      - fake-bittrex
    expose:
      - 3333
      - 4444
    networks:
      - lbry
      
  reflector:
    build: ./lbrynet
    depends_on:
      - lbryum-server
      - dht
      - fake-bittrex
    environment:
      - LBRY_RUN_REFLECTOR_SERVER=true
    expose:
      - 3333
      - 4444
      - 5566
    networks:
      - lbry
      
  lbrynet:
    build: ./lbrynet
    depends_on:
      - lbryum-server
      - dht
      - fake-bittrex
      - reflector
    environment:
      # want to be able to access this from the host
      - LBRY_API_INTERFACE=0.0.0.0
    ports:
      # the ui and the api port
      - 5279:5279
    expose:
      - 3333
      - 4444
    networks:
      - lbry

  fake-bittrex:
    build: ./fake-bittrex
    expose:
      - 8003
    networks:
      - lbry
